- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/samueldannatt/name-stats
  - name: clone repo
    git:
      repo: git@github.com:SamusDD/ttc.git
      dest: /home/samueldannatt/properproject
      clone: yes
  vars:
    docker_user: samueldannatt

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: samueldannatt
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: samueldannatt 